# Generated by Django 3.0.1 on 2020-01-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chair',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sofa',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('Available', 'Item ready to be purchased'), ('Sold', 'Item is Sold'), ('Restocking', 'Item restocking in few days')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='chair',
            name='status',
            field=models.CharField(choices=[('Available', 'Item ready to be purchased'), ('Sold', 'Item is Sold'), ('Restocking', 'Item restocking in few days')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='sofa',
            name='status',
            field=models.CharField(choices=[('Available', 'Item ready to be purchased'), ('Sold', 'Item is Sold'), ('Restocking', 'Item restocking in few days')], default='Available', max_length=50),
        ),
    ]
